export const INCREASE_COUNT = "INCREASE_COUNT";
export const INCREASE_COUNT_SUCCESS = "INCREASE_COUNT_SUCCESS";

export const DECREASE_COUNT = "DECREASE_COUNT";
export const DECREASE_COUNT_SUCCESS = "DECREASE_COUNT_SUCCESS";

export const MULTIPLE_NUMBERS = "MULTIPLE_NUMBERS";

export const GET_DATA_SUCCESS = "GET_DATA_SUCCESS";

export const GET_ANTIQUE_ITEM_REQUEST = "GET_ANTIQUE_ITEM_REQUEST";
export const GET_ANTIQUE_ITEM_REQUEST_SUCCESS = "GET_ANTIQUE_ITEM_REQUEST_SUCCESS";